name: Update Proxies

on:
  schedule:
    - cron: '0 */3 * * *'  # This schedules the job to run every 3 hours
  workflow_dispatch:

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust the Python version as needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download updater.py
        run: curl -s -L ${{ secrets.UPDATER }} -o updater.py

      - name: Run the updater script
        run: python updater.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f http.txt socks4.txt socks5.txt README.md
          git commit -m "Update proxy lists and README" -a || echo "No changes to commit"
          git push
